-- Build-time generator: config.lua + assets/index.html  ->  C header (stdout).
-- usage: lua tools/gen.lua config.lua assets/index.html > config_gen.h

local cfg_path, html_path = arg[1], arg[2]

local function fail(msg)
  io.stderr:write("config error: ", tostring(msg), "\n")
  os.exit(1)
end

local chunk, err = loadfile(cfg_path)
if not chunk then fail(err) end
local ok, cfg = pcall(chunk)
if not ok then fail(cfg) end
if type(cfg) ~= "table" then fail(cfg_path .. " must `return { ... }`") end

-- C string literal escaping
local function esc(s)
  return (s:gsub('[%c"\\]', function(c)
    if c == "\n" then return '\\n"\n"' end
    return string.format("\\%03o", c:byte())
  end))
end
local function lit(s) return '"' .. esc(s) .. '"' end

local function int(v, default, name)
  v = v == nil and default or v
  if type(v) ~= "number" or v < 1 then fail("'" .. name .. "' must be a positive number") end
  return math.floor(v)
end

local engines = cfg.engines
if type(engines) ~= "table" or #engines == 0 then
  fail("'engines' must be a non-empty list")
end

local out, default_idx = {}, nil
local function w(...) out[#out + 1] = string.format(...) end

w("/* generated by tools/gen.lua - do not edit */\n")
w("typedef struct { const char *name, *prefix, *suffix; } Engine;\n")
w("static const Engine engines[] = {\n")
for i, e in ipairs(engines) do
  if type(e) ~= "table" or type(e.name) ~= "string" or type(e.url) ~= "string" then
    fail(("engine #%d needs string fields 'name' and 'url'"):format(i))
  end
  local pre, post = e.url:match("^(.-)%%s(.*)$")
  if not pre or post:find("%%s") then
    fail(("engine '%s': url must contain exactly one %%s"):format(e.name))
  end
  if e.name == cfg.default then default_idx = i - 1 end
  w("\t{ %s, %s, %s },\n", lit(e.name), lit(pre), lit(post))
end
w("};\n")

if cfg.default ~= nil and not default_idx then
  fail(("default engine '%s' is not in the engines list"):format(tostring(cfg.default)))
end

w("#define N_ENGINES %d\n", #engines)
w("#define DEFAULT_ENGINE %d\n", default_idx or 0)
w("#define WIN_W %d\n", int(cfg.width, 1000, "width"))
w("#define WIN_H %d\n", int(cfg.height, 720, "height"))
w("#define START_DARK %d\n", cfg.dark and 1 or 0)
w("#define DOWNLOAD_DIR %s\n",
  type(cfg.download_dir) == "string" and lit(cfg.download_dir) or "NULL")

local f = assert(io.open(html_path, "rb"))
local html = f:read("a")
f:close()
w("static const char HOME_HTML[] =\n\"%s\";\n", esc(html))

io.write(table.concat(out))
